version: "3.1"
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
  redis:
    image: redis:6.2.5-alpine
    container_name: redis
    restart: always
    ports:
      - ${DB_PORT_REDIS}:6379
    
